name: create-pdfs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -v $PWD:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf ProcessDescription/main.adoc -o output.pdf
